name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cffi=1.11.5
  - chardet=3.0.4
  - conda=4.6.8
  - conda-env=2.6.0
  - cryptography=2.4.2
  - idna=2.8
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libstdcxx-ng=8.2.0
  - ncurses=6.1
  - openssl=1.1.1b
  - pip=18.1
  - pycosat=0.6.3
  - pycparser=2.19
  - pyopenssl=18.0.0
  - pysocks=1.6.8
  - python=3.7.1
  - readline=7.0
  - requests=2.21.0
  - ruamel_yaml=0.15.46
  - setuptools=40.6.3
  - six=1.12.0
  - sqlite=3.26.0
  - tk=8.6.8
  - urllib3=1.24.1
  - wheel=0.32.3
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
prefix: /opt/miniconda3

